--- # regions specifications, rectangular and polynomial

# rectangular on lat lon, or bounded by lat
rect:
    mwam4:
        llcrnrlon: -32.
        llcrnrlat: 42.
        urcrnrlon: 94.
        urcrnrlat: 84.
    vietnam:
        llcrnrlon:
        llcrnrlat:
        urcrnrlon:
        urcrnrlat:

# polynomial
poly:
    NorwegianSea:
        lats: [62.1,62.3,63.2,64.7,68.5,71.1,72.6,74.0,76.9,
                76.3,74.5,70.2,68.3,66.0,64.1,62.1]
        lons: [5.1,-0.8,-6.6,-9.6,-8.6,-7.5,1.7,8.5,7.2,16.8,
                18.7,22.6,18.4,14.7,11.7,5.1]
