--- # specifications for satellite missions

########################################################################
# """
# general structure:
#       + product (eumetsat/cmems)
#           + specs
# """
########################################################################

eumetsat_L2:
    mission:
        s3a: S3A
        s3b: S3B
    dst:
        path_template: /home/patrikb/tmp_altimeter/L2/mission
        file_template: "varalias_mission_region_\
                        %Y%m%d%H%M%S_%Y%m%d%H%M%S.nc"
        strsub: ['varalias','mission','region']
        file_date_incr: d
    src:
        api_url: ["https://colhub.met.no/",
                  "https://colhub-archive.met.no/",
                  "https://coda.eumetsat.int/search"]
    misc:
        kwargs: # specify dict for query
    vardef: # varalias: varname
        Hs: swh_ocean_20_ku
        lats: lat_20_ku
        lons: lon_20_ku
        time: time_20_ku
    processing_level: L2
    provider: eumetsat

cmems_L3_NRT:
    mission:
        s3a: s3a
        s3b: s3b
        c2: c2
        al: al
        j3: j3
        h2b: h2b
        cfo: cfo
    dst:
        path_template: /home/patrikb/tmp_altimeter/L3/mission
        file_template: "varalias_mission_region_\
                        %Y%m%d%H%M%S_%Y%m%d%H%M%S.nc"
        strsub: ['varalias','mission','region']
        file_date_incr: m
    src:
        path_template: "/Core/\
                        WAVE_GLO_PHY_SWH_L3_NRT_014_001/\
                        cmems_obs-wave_glo_phy-swh_nrt_mission-l3_PT1S/\
                        %Y/%m/"
                        #WAVE_GLO_WAV_L3_SWH_NRT_OBSERVATIONS_014_001/\
                        #dataset-wav-alti-l3-swh-rt-global-mission/%Y/%m/"
        server: "nrt.cmems-du.eu"
        strsub: ['mission']
    misc:
    vardef: # varalias: varname
        Hs: VAVH
        U: WIND_SPEED
    processing_level: L3
    provider: cmems

cmems_L3_NRT_sla:
    mission:
        h2c: h2c
        j3: j3
        s6a: s6a
    dst:
        path_template: /home/patrikb/tmp_altimeter/L3/SSH/mission
        file_template: "varalias_mission_region_\
                        %Y%m%d%H%M%S_%Y%m%d%H%M%S.nc"
        strsub: ['varalias','mission','region']
        file_date_incr: m
    src:
        path_template: "/Core/\
                        SEALEVEL_GLO_PHY_L3_NRT_OBSERVATIONS_008_044/\
                        dataset-duacs-nrt-global-mission-phy-l3/\
                        %Y/%m/"
                        #cmems_obs-wave_glo_phy-swh_nrt_mission-l3_PT1S/\
                        #WAVE_GLO_WAV_L3_SWH_NRT_OBSERVATIONS_014_001/\
                        #dataset-wav-alti-l3-swh-rt-global-mission/%Y/%m/"
        server: "nrt.cmems-du.eu"
        strsub: ['mission']
    misc:
    vardef: # varalias: varname
        sla: sla
    processing_level: L3
    provider: cmems


cmems_L3_s6a:
    mission:
        s6a: s6a
    dst:
        path_template: /home/patrikb/tmp_altimeter/L3/mission
        file_template: "varalias_mission_region_\
                        %Y%m%d%H%M%S_%Y%m%d%H%M%S.nc"
        strsub: ['varalias','mission','region']
        file_date_incr: m
    src:
        path_template: "/Core/\
                WAVE_GLO_PHY_SWH_L3_NRT_014_001/\
                cmems_obs-wave_glo_phy-swh_nrt_mission-l3_PT1S/%Y/%m/"
                # or
                #WAVE_GLO_WAV_L3_SWH_NRT_OBSERVATIONS_014_001/\
                #cmems_obs-wave_glo_phy-swh_nrt_s6a-l3_PT1S_Prev/\
                #/%Y/%m/"
                # or
                #WAVE_GLO_PHY_SWH_L3_NRT_014_001/\
                #WAVE_GLO_WAV_L3_SWH_NRT_OBSERVATIONS_014_001_Prev/\
                #cmems_obs-wave_glo_phy-swh_nrt_mission-l3_PT1S/%Y/%m/"
        server: "nrt.cmems-du.eu"
        strsub: ['mission']
    misc:
    vardef: # varalias: varname
        Hs: VAVH
        U: WIND_SPEED
    processing_level: L3
    provider: cmems

cmems_L3_MY:
    mission:
        c2: c2
        al: al
        j1: j1
        j2: j2
        j3: j3
        cfo: cfo
        env: en
    dst:
        path_template: /home/patrikb/tmp_altimeter/L3/MY/mission
        file_template: "varalias_mission_region_\
                        %Y%m%d%H%M%S_%Y%m%d%H%M%S.nc"
        strsub: ['varalias','mission','region']
        file_date_incr: m
    src:
        path_template: "/Core/WAVE_GLO_PHY_SWH_L3_MY_014_005/cci_obs-wave_glo_phy-swh_my_mission-l3_PT1S/%Y/%m/"
        server: "my.cmems-du.eu"
        strsub: ['mission']
    misc:
    vardef: # varalias: varname
        Hs: VAVH
    processing_level: L3
    provider: cmems

cmems_L3_MY_SAR:
    mission:
        s1a: s1a
        s1b: s1b
    dst:
        path_template: /home/patrikb/tmp_SAR/L3/MY/mission
        file_template: "varalias_mission_region_\
                        %Y%m%d%H%M%S_%Y%m%d%H%M%S.nc"
        strsub: ['varalias','mission','region']
        file_date_incr: m
    src:
        path_template: "/Core/WAVE_GLO_PHY_SPC_L3_MY_014_006/dataset-wav-sar-l3-spc-rep-global-mission/%Y/%m/"
        unique_file_chars: '-3H-'
        server: "my.cmems-du.eu"
        strsub: ['mission']
    misc:
    vardef: # varalias: varname
        Hs: SWH
    processing_level: L3
    provider: cmems

cci_L2P:
    mission:
        j1: jason-1
        j2: jason-2
        j3: jason-3
        c2: cryosat-2
        env: envisat
        ers1: ers-1
        ers2: ers-2
        gfo: gfo
        al: saral
        tpx: topex
    dst:
        path_template: /home/patrikb/tmp_altimeter/L2P/mission
        file_template: "varalias_mission_region_\
                        %Y%m%d%H%M%S_%Y%m%d%H%M%S.nc"
        strsub: ['varalias','mission','region']
        file_date_incr: m
    src:
        path_template: "/neodc/esacci/sea_state/data/v1.1_release/\
                        l2p/mission/v1.1/%Y/%m/%d/"
        #file_template: "ESACCI-SEASTATE-L2P-SWH-Jason-3-\
        #                %Y%m%dT%H*-fv01.nc"
        server: "ftp.ceda.ac.uk"
        strsub: ['mission']
    misc:
    vardef: # varalias: varname
        Hs: swh_denoised # time
        U: wind_speed_alt # time
        time: time
        lats: lat
        lons: lon
    processing_level: L2P
    provider: cci

cci_L3:
    mission:
        multi: multi
    dst:
        path_template: /home/patrikb/tmp_altimeter/L3/mission
        file_template: "varalias_mission_region_\
                        %Y%m%d%H%M%S_%Y%m%d%H%M%S.nc"
        strsub: ['varalias','mission','region']
        file_date_incr: m
    src:
        path_template: "/neodc/esacci/sea_state/data/v1.1_release/\
                        l3/v1.1/%Y/%m/%d/"
        server: "ftp.ceda.ac.uk"
        strsub: ['mission']
    misc:
    vardef: # varalias: varname
        Hs: swh_denoised # time
        U: wind_speed_alt # time
        time: time
        lats: lat
        lons: lon
    processing_level: L3
    provider: cci

L2_20Hz_s3a:
    mission:
        s3a: s3a
    dst:
        path_template: "/home/patrikb/tmp_altimeter/20Hz/mission"
        file_template: "varalias_mission_region_\
                        %Y%m%d%H%M%S_%Y%m%d%H%M%S.nc"
        strsub: ['varalias','mission','region']
        file_date_incr: m
    src:
        path_template: "/products/v3/data/satellite/altimeter/\
                        l2_20Hz/l2/sentinel-3_a/%Y/%j/" # year/day-of-year
        server: "eftp.ifremer.fr"
        strsub: ['mission']
        file_search_template: '%Y%m%d'
        date_incr: d
    misc:
    vardef: # varalias: varname
        Hs: swh_lrrmc_corr_hfa_20_ku # time
        time: time_echo_sar_ku
        lats: lat_echo_sar_ku
        lons: lon_echo_sar_ku
    processing_level: L3
    provider: ifremer

L2_20Hz_c2:
    mission:
        c2: cryosat-2
    dst:
        path_template: /home/patrikb/tmp_altimeter/20Hz/mission
        file_template: "varalias_mission_region_\
                        %Y%m%d%H%M%S_%Y%m%d%H%M%S.nc"
        strsub: ['varalias','mission','region']
        file_date_incr: m
    src:
        path_template: "/products/v3/data/satellite/altimeter/\
                        l2_20Hz/l2/cryosat-2/%Y/%j/" # year/day-of-year
        server: "eftp.ifremer.fr"
        strsub: ['mission']
        file_search_template: '%Y%m%d'
        date_incr: d
    misc:
    vardef: # varalias: varname
        Hs: swh_lrrmc_corr_hfa_20_ku # time
        time: time_echo_sar_ku
        lats: lat_echo_sar_ku
        lons: lon_echo_sar_ku
    processing_level: L3
    provider: ifremer

cnes_5Hz_my:
    mission:
        h2b: h2b
        cfo: cfo
        j3: j3
        al: al
    dst:
        # https://tds.aviso.altimetry.fr/thredds/catalog/dataset-duacs-wave-experimental-along-track/catalog.html
        path_template: /home/patrikb/tmp_altimeter/exp/mission
        file_template: "varalias_mission_region_\
                        %Y%m%d%H%M%S_%Y%m%d%H%M%S.nc"
        strsub: ['varalias','mission','region']
        file_date_incr: m
    src:
        path_template: "/Intermediate/WAVE_GLO_PHY_SWH_L3_MY_014_008/\
                        cnes_obs-wave_glo_phy-swh_my_h2b-l3_PT0.2S/%Y/%m/"
        #server: "ftp-access.aviso.altimetry.fr"
        server: "my.cmems-du.eu"
        strsub: ['mission']
        file_search_template: '%Y%m%d'
    misc:
    vardef: # varalias: varname
        Hs: VAVH
    processing_level: L3
    provider: cnes


cfo_swim_L2P:
    mission:
        cfo: cfo
    dst:
        path_template: /home/patrikb/tmp_SWIM/L2P/mission
        file_template: "varalias_mission_swim_region_\
                        %Y%m%d%H%M%S_%Y%m%d%H%M%S.nc"
        strsub: ['varalias','mission','region']
        file_date_incr: m
    src:
        path_template: '/cfosat/swim_l2p_box_nrt/%Y/'
        server: "ftp-access.aviso.altimetry.fr"
        strsub: ['mission']
    misc:
    vardef: # varalias: varname
        Hs: wave_param
        Hs_idx: '[0,0,:]'
        Pdir: wave_param
        Pdir_idx: '[2,0,:]'
        Lp: wave_param
        Lp_idx: '[1,0,:]'
        spec2d: pp_mean
        spec2d_idx: '[:,:,0,10]'
        time: time_spec_l2
        time_idx: '[0,:]'
        lats: lat_spec_l2
        lats_idx: '[0,:]'
        lons: lon_spec_l2
        lons_idx: '[0,:]'
        convention: oceanographic
    processing_level: L2P
    provider: aviso
