--- # specifications for validation related tasks

insitu:
    dst:
        path_template:
        file_template:
        strsub:
satellite_altimeter:
    dst:
        path_template: "/home/patrikb/tmp_validation/model/%Y/%m/"
        file_template: "varalias_model_vs_mission_for_region_val_ts_\
                        ltleadtimestr_%Y%m.nc"
        strsub: ['varalias','model','mission','region','leadtimestr']
