name: Black

on:
  push:
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Check formatting with Black
        uses: psf/black@stable
        with:
          options: "--check --diff"
